### ISSUE TITLE
Circle CI の設定をする

### ISSUE THREAD

**Issue by yumechi** [yumechi/gishohaku1-yumechi#5]
# 概要

技術書典6でやっていたDropboxへのビルド処理をまたやる。そのためにCircle CIを導入する。

# やること

Circle CIでPDFをビルドして、Dropboxに投げ込む

# 課題点

なし

**Comment by yumechi** [comment]
こんな感じのファイルだったらしい

```yml
version: 2
jobs:
  build:
    docker:
        - image: vvakame/review:3.1
    branches:
      only:
        - master
        - develop
    steps:
      - checkout
      - run:
          name: Build PDF
          command: rake clean pdf
          working_directory: ./colab-book
      - store_artifacts:
          path: ./colab-book/book.pdf
          destination: book.pdf
      - run:
          name: Upload to Dropbox
          command: ./upload_dropbox.sh ./colab-book/book.pdf ${DROPBOX_TOKEN}
      - run:
          name: show share folder
          command: echo "show Dropbox のこの辺を見ろ”
```
